services:
  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: src/AuthenticationService/Dockerfile
      
  # ==========================================
  # 2. workoutservice Service 
  # ==========================================
  workoutservice:
    image: ${DOCKER_REGISTRY-}workoutservice
    build:
      context: .
      dockerfile: src/WorkoutService/Dockerfile

  # ==========================================
  # 3. userprofileservice Service 
  # ==========================================
  userprofileservice:
    image: ${DOCKER_REGISTRY-}userprofileservice
    build:
      context: .
      dockerfile: src/UserProfileService/Dockerfile